broker-host: "${MQTT_HOSTNAME}"
broker-user: "${MQTT_USERNAME}"
broker-pwd: "${MQTT_PASSWORD}"
broker-port: 1883
mapping-type: topic-pair
publish-topic: linky
publish-extend: true
to-mqtt:
  event:
    # auto-register to following events
    registrations:
      - api: linky
        verb: SINSTS
        args:
          action: subscribe
      - api: linky
        verb: URMS
        args:
          action: subscribe
      - api: linky
        verb: IRMS
        args:
          action: subscribe
      - api: linky
        verb: energy
        args:
          action: subscribe
    template:
      data: "%{data}"
